# Generated by Django 4.2 on 2023-11-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='rattached_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediacenter.filesmodel'),
        ),
    ]
