# Generated by Django 4.2 on 2023-10-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmodel',
            name='resolutions',
        ),
    ]
