# Generated by Django 4.2 on 2023-10-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0003_remove_filesmodel_resolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='resolutions',
            field=models.JSONField(blank=True, default={'height': None, 'width': None}, null=True),
        ),
    ]
