# Generated by Django 4.2 on 2023-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0003_filesmodel_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='resolutions',
            field=models.JSONField(blank=True, default={'heigth': None, 'width': None}, null=True),
        ),
    ]
