# Generated by Django 4.2 on 2023-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0004_filesmodel_resolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='resolutions',
            field=models.JSONField(blank=True, default={'height': None, 'width': None}, null=True),
        ),
    ]
